import type { Metadata } from "next";
import Header from "../../components/Header";
import "../globals.css"
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const user = "admin"
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-h-screen">
                <Header />
                {children}
            </body>
        </html>
    );
}
