name: test ci cd labled         # optional, just a label

on:                         # WHEN to trigger
  push:
    branches:
      - main

jobs:                      
  job-name: test ci cd
    runs-on: ubuntu-latest  
    steps:                  
      - name: Step 1 name
        run: echo "hello"