name: lms deploy      

on:                         
  push:
    branches:
      - main

jobs:             
  pull: 
    runs-on: ubuntu-latest  
    steps:                  
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/lms

            git pull origin main

            docker compose down

            docker rmi -f lms-client:latest lms-server:latest
            
            docker compose up -d 
